### ISSUE TITLE
Unexplained lines of code in ch21.py.

### ISSUE THREAD

**Issue by cjwyett** [DrRyanMc/CompNucEng#2]
Hi again,

I'm having a hard time trying to figure out some code in slab_transmission. There is no explanation in the textbook, any help would be greatly appreciated.   

 **Lines 74-78 of ch21.py**
```
           #make sure that l is not too large
            if (mu > 0):
                l = np.min([l,(3-x)/mu]) 
            else:
                l = np.min([l,-x/mu])

```
Where does 3 come from? 
How does this work? 
How is it ok to replace our previously calculated L  with `(-x)/mu` or `(3-x)/mu`?   

**Lines 86 - 91 of ch21.py**

```
            #still in the slab?
            if (np.abs(x-thickness) < 1.0e-14):
                transmission += weight
                alive = 0
            elif (x<= 1.0e-14):
                alive = 0
```
Where does 1e-14 come from?

**Comment by DrRyanMc** [comment]
The issue was that the 3 should have been thickness. That line moved the particle to the edge if it was going to move beyond it.  

The second batch was checking to see if the particle was just at the edge.  It is a good idea to not use == with floating point numbers because small (e.g. 1e-10 sized) errors could cause the statement to not evaluate as true. That is why I try to see if the number is within something small rather than check if they are equal.

**Comment by cjwyett** [comment]
Thanks!
